define ['cs!./new-book', 'cs!./new-module'], (newBook, newModule) ->
  module = newModule {title: 'Module in a Book with a Chapter', body: '<p>Nothing</p>'}
  return {
    content: [
      module
      newBook
        title: 'Book with a Chapter'
        body: """
          <nav>
            <ol>
              <li>
                <span>A Chapter</span>
                <ol>
                  <li>
                    <a href='#{module.id}' class='autogenerated-text'>[THIS TITLE SHOULD NOT BE VISIBLE]</a>
                  </li>
                </ol>
              </li>
            </ol>
          </nav>
        """
    ]
  }
