// Generated by CoffeeScript 1.6.3
(function() {
  define(['aloha', 'aloha/plugin'], function(Aloha, Plugin) {
    return Plugin.create('ghbook-image', {
      init: function() {
        return Aloha.require(['assorted/image'], function(Image) {
          return Image.uploadImage = function(file, el, callback) {};
        });
      }
    });
  });

}).call(this);
