// Generated by CoffeeScript 1.3.3
(function() {

  define(['backbone'], function(Backbone) {
    var MEDIA_TYPES, MediaTypes;
    MediaTypes = Backbone.Collection.extend({
      model: Backbone.Model.extend({
        sync: function() {
          throw 'This model cannot be syncd';
        }
      }),
      sync: function() {
        throw 'This model cannot be syncd';
      }
    });
    MEDIA_TYPES = new MediaTypes();
    return {
      add: function(modelType) {
        var mediaType;
        mediaType = modelType.prototype.mediaType;
        return MEDIA_TYPES.add({
          id: mediaType,
          modelType: modelType
        }, {
          merge: true
        });
      },
      get: function(mediaType) {
        var modelType;
        modelType = MEDIA_TYPES.get(mediaType);
        if (!modelType) {
          console.error("ERROR: No editor for media type '" + mediaType + "'. Help out by writing one!");
          modelType = MEDIA_TYPES.models[0];
        }
        return modelType.get('modelType');
      },
      list: function() {
        var type;
        return (function() {
          var _i, _len, _ref, _results;
          _ref = MEDIA_TYPES.models;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            type = _ref[_i];
            _results.push(type.get('id'));
          }
          return _results;
        })();
      },
      asCollection: function() {
        return MEDIA_TYPES;
      }
    };
  });

}).call(this);
